version: 2

mkdocs: {}  # tell readthedocs to use mkdocs

python:
  version: 3.8
  install:
  - method: pip
    path: .
    extra_requirements:
    - rtd
  - requirements: docs/.readthedocs-requirements.txt
