# Safety Security and License Configuration file
# https://docs.pyup.io/docs/safety-20-policy-file

security:
    ignore-cvss-severity-below: 0
    ignore-cvss-unknown-severity: False
    ignore-vulnerabilities:
        70612:  # Vulnerability found in jinja2 version 3.1.4 - https://data.safetycli.com/v/70612/97c
            expires: '2024-12-30'
        66742:  # Vulnerability found in black version 23.12.1 - https://data.safetycli.com/v/66742/97c
            expires: '2024-12-30'

    continue-on-vulnerability-error: False
