
name: env-alias
version: 0.3.7
author: Nicholas de Jong <contact@nicholasdejong.com>
license: BSD2
description: Powerful helper utility to create shell alias commands to easily set collections of environment variables often with secret values from a variety of data-sources and data-formats.
url: https://env-alias.readthedocs.io/

typed: false

entrypoints:
  console_scripts:
    - env-alias = env_alias.cli.entrypoints:env_alias
    - env-alias-generator = env_alias.cli.entrypoints:env_alias_generator

test-drivers:
  - type: pytest
    parallelism: 8
  - type: pylint
    args: [ '--fail-under=9.0', '--ignore=vendor', '--ignore=tests', '--indent-string="    "', '--disable=W1202,W1203,C0209' ]

templates:
  - type: pylintrc
    use: shut

requirements:
  - python ^3.6
  - pyyaml

classifiers:
  - "Environment :: Console"
  - "Intended Audience :: Developers"
  - "Intended Audience :: Information Technology"
  - "Programming Language :: Python :: 3.6"
  - "Programming Language :: Python :: 3.7"
  - "Programming Language :: Python :: 3.8"
  - "Programming Language :: Python :: 3.9"
  - "License :: OSI Approved :: BSD License"

keywords:
  - 'env-alias'
  - 'shell'
  - 'env'
  - 'alias'
  - 'bash'
