
name: env-alias
version: 0.3.5
author: Nicholas de Jong <contact@nicholasdejong.com>
license: BSD2
description: Powerful helper utility to create shell alias commands to easily set collections of environment variables often with secret values from a variety of data-sources and data-formats.
url: https://env-alias.readthedocs.io/

typed: false

entrypoints:
  console_scripts:
    - env-alias = env_alias.cli.entrypoints:env_alias
    - env-alias-generator = env_alias.cli.entrypoints:env_alias_generator

test-driver:
  type: pytest

requirements:
  - python ^3.6
  - pyyaml

classifiers:
  - "Environment :: Console"
  - "Intended Audience :: Developers"
  - "Intended Audience :: Information Technology"
  - "Programming Language :: Python :: 3.6"
  - "Programming Language :: Python :: 3.7"
  - "Programming Language :: Python :: 3.8"
  - "License :: OSI Approved :: BSD License"

keywords:
  - 'env-alias'
  - 'shell'
  - 'env'
  - 'alias'
  - 'bash'
