name: docs

on:
  pull_request:
  push:
    branches: ["main"]

env:
  PYTHON_VERSION: "3.12"

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with: { python-version: "${{ env.PYTHON_VERSION }}" }

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Build docs
        run: |
          cd docs
          uv sync --frozen
          uv run mkdocs build --strict

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write

    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install Python
        uses: actions/setup-python@v5
        with: { python-version: "${{ env.PYTHON_VERSION }}" }

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Deploy docs to GitHub Pages
        run: |
          cd docs
          uv sync --frozen
          uv run mkdocs gh-deploy --force
